### ISSUE TITLE
Transmission progress-bar hidden

### ISSUE THREAD

**Issue by bomwoll** [shimmerproject/Greybird#149]
First of all sorry for my - maybe - bad english i'm french.

There is an issue with the progress-bar in Transmission under xubuntu  16.04 - I don't try it on other distribution. 
As you can see in this screenshot - http://pix.toile-libre.org/?img=1474119567.png - when I focus on a working torrrent, the progress-bar is entirely blue, even if the torrent is unfinished. In this screenshot the torrent is only 1.8% finish.
However the bug don't affect the stopped torrent, like show in this screenshot - http://pix.toile-libre.org/?img=1474119762.png.

**Comment by ochosi** [comment]
This bug should be fixed in Xubuntu 16.10 with Greybird 3.20.1 and Gtk+3.20.x.

I'm not sure I'll have time to investigate and fix a small visual glitch like this one and backport it to 16.04. Patches are welcome though!

**Comment by kiplingw** [comment]
I'm actually still having this problem, or perhaps a related one. In my case the progress bar is gone entirely in Transmission. I'm using Xubuntu 16.10. https://imagebin.ca/v/2wvQHXbMWkeR

**Comment by ochosi** [comment]
@kiplingw What theme is that? It sure doesn't look like Greybird.

**Comment by kiplingw** [comment]
@ochosi You're right. My bad. That's Blackbird.

**Comment by ochosi** [comment]
Alrighty. Anyway, this issue is fixed with Greybird 3.20.x
