### ISSUE TITLE
Inner space in Synaptic borders

### ISSUE THREAD

**Issue by jEsuSdA** [shimmerproject/Greybird#196]
While making the #195 issue, I realized there are the same problem with Synaptic and it's panel borders:

Here you can see and old (and not mine) Synaptic screenshot with previous version of Greybird:

![screenshot26](https://user-images.githubusercontent.com/5833446/27682207-0ad3be1a-5cc2-11e7-98c0-fe9796477496.png)

And here, you can she how looks like Synaptic with nowadays Greybird version:

![screenshot27](https://user-images.githubusercontent.com/5833446/27682224-1bbe15c2-5cc2-11e7-9dc2-c91f9385474b.png)

Look at that:

![screenshot28](https://user-images.githubusercontent.com/5833446/27682325-6b124c10-5cc2-11e7-93c4-d08b44ab0734.png)

There is no any padding between the panel content and the borders, so the borders are almost over the buttons and other content. 

I think the old one looks like much better than now. What do you think?

Thanks!! ;)

**Comment by ochosi** [comment]
The old one is Gtk2 and the new one is Gtk3. The application developers control that type of padding so there isn't much I can do about it...

**Comment by jEsuSdA** [comment]
Submitted to Synaptic mantainers. I hope they can fix it. ;)

**Comment by soc** [comment]
@jEsuSdA I'm fixing this in https://github.com/mvo5/synaptic/pull/30.

Combined with the fixes for #227 and #228 Synaptic looks like this now:

![synaptic-better](https://user-images.githubusercontent.com/42493/45330256-dd5cbe80-b564-11e8-9c26-90689c174dfb.png)

**Comment by jEsuSdA** [comment]
@soc Great work!! Thanks a lot!

**Comment by bluesabre** [comment]
Fixed upstream per @soc's comment, closing this issue.

**Comment by soc** [comment]
Thanks!

**Comment by soc** [comment]
Hey @bluesabre, this isn't fixed, the second commit from #232 has not been merged.
I tried to ping people regarding the status of that PR, but didn't receive a reply.
