### ISSUE TITLE
GTK 3.16

### ISSUE THREAD

**Issue by questmark** [shimmerproject/Greybird#84]
GNOME 3.16 has been out for some time now and I was wondering if there are plans to update this theme to work with GTK+ 3.16?

**Comment by ochosi** [comment]
Uhm, you have a funny perception of "a while", it's been less than a month. Also, what problems did you encounter with Gtk3.16 specifically? Judging from the changelog, there shouldn't really be any big issues with it.

**Comment by questmark** [comment]
>you have a funny perception of "a while"

Every day spent with the default Adwaita theme feels like an eternity.

The biggest issue I noticed were the huge black borders around windows.
http://imgur.com/LpZ2MPy
Those put me off from actually using it for now, but I guess I could try and report more issues (if there are any).

**Comment by ochosi** [comment]
Alright, so what desktop environment are you on there? Does it have compositing? What happens if you restart that same app when it has the black borders – do they go away?

**Comment by questmark** [comment]
>what desktop environment are you on there? Does it have compositing?

The window manager is Openbox, with no compositor.

Unrelated to the Greybird theme, but it appears that the huge borders are a side effect of the "old" themes when they're used with GTK+ 3.16. In the thread linked below, the person was experiencing the same issue with a different (old) theme, even with a different window manager and compositing enabled (and disabled).
https://bbs.archlinux.org/viewtopic.php?id=195872

>What happens if you restart that same app when it has the black borders – do they go away?

They don't. The borders appear consistently.

**Comment by ochosi** [comment]
Got it. I just pushed a hypothetical fix to git master, could you test it?

**Comment by questmark** [comment]
It changed the color, but it's still there.
http://i.imgur.com/KPYC81s.png

Just to make sure, I installed a compositor (Compton) and even with compositing, it's still appearing.

**Comment by ochosi** [comment]
Alright, guess they added more new classes for the CSDs with 3.16. Will have to read up on that.

**Comment by ochosi** [comment]
Pushed another small improvement. As I can't test it, I'm not sure it'll fix it. But give it a try!

**Comment by questmark** [comment]
Yes, it fixed it. Thanks!
http://imgur.com/ztxYmMu

I'll keep looking in case more minor issues appear.

**Comment by ochosi** [comment]
Awesome :)
I made the border color a bit less harsh now. Let me know whether other issues come up, meanwhile I'll close this issue. Cheers!
